const Actions = {
  TRY_QUERY: "TRY_QUERY",
  ACCEPT: "ACCEPT",

  REVERT: "REVERT",
  SET_STATUS: "SET_STATUS",
  SET_QUERY: "SET_QUERY",
  RESET_RESPONSES: "RESET_RESPONSES",

  SET_SESSION_ID: "SET_SESSION_ID",
  CLEAR: "CLEAR",
  SIGN_IN: "SIGN_IN",
}

export default Actions
